### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by ziggylazer** [pyro57/pyrosploit#1]
System settings: 
Win 10. VM. Bridged connection. 
All Firewalls disabled 

Parrot Linux
Open ports

While running quick_start user input is needed in the form of inerface IP, target IP. Handler port and stager port. 
When all these parameters are given and I check netstat and ss + logs I dont see any connection being made.

**Comment by pyro57** [comment]
We figured this out, gonna go ahead and close this issue.
